name: "Terraform - Features"
on:
  push:
    branches-ignore:
      - main
      - uat
      - dev
      - platform-engineering

jobs:
  terraform:
    name: Terraform
    runs-on: self-hosted
    strategy:
      matrix:
        component-path: 
          [ 
            "10-platform-engineering/11-terraform-state",
            "10-platform-engineering/12-network",
            "10-platform-engineering/13-cicd-agent",
            "20-app-infra/21-network",
            "20-app-infra/22-security-groups", 
            "20-app-infra/23-data-base", 
            "20-app-infra/24-instances" 
            ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.8
      
      - name: Terraform Format
        working-directory: ${{ matrix.component-path }}
        run: terraform fmt -check
        
      - name: Terraform Init
        working-directory: ${{ matrix.component-path }}
        run: terraform init  -backend-config=../../backend_config.hcl

      - name: Terraform Validate
        working-directory: ${{ matrix.component-path }}
        run: terraform validate -no-color
